#!/bin/bash
# gen_layout.sh — regenerate src/c_layout.zig from ground-truth C struct offsets.
#
# Compiles tools/offsets.c under BOTH build configs (production library and the
# --dev testfixture) and emits a Zig file whose constants the struct mirrors in
# the ported modules assert against at comptime. Re-run whenever offsets.c gains
# a field or the vendored SQLite sources are bumped.
#
# Usage: tools/gen_layout.sh
set -euo pipefail
PROJ="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJ"

# Production library flags — keep in sync with `sqlite_flags` in build.zig.
PROD_FLAGS=(
  -DSQLITE_CORE=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS
  -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE
  -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK
  -DSQLITE_ENABLE_CARRAY -DSQLITE_ENABLE_MEMSYS5 -DSQLITE_ENABLE_PERCENTILE
  -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_STMTVTAB
  -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC
  -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_EXPLAIN_COMMENTS
  -DSQLITE_DQS=0 -DSQLITE_HAVE_ZLIB=1
)

# --dev testfixture flags — the layout-affecting subset of what `configure --dev`
# passes (see build/gen/make_tf.log). SQLITE_DEBUG/SQLITE_TEST are the ones that
# move struct layouts; the feature flags match the testfixture build.
TF_FLAGS=(
  -DSQLITE_CORE=1 -DSQLITE_THREADSAFE=1 -DSQLITE_DEBUG=1 -DSQLITE_TEST=1
  -DSQLITE_CRASH_TEST=1 -DSQLITE_DEFAULT_PAGE_SIZE=1024 -DSQLITE_NO_SYNC=1
  -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5
  -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_SESSION
  -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_CARRAY -DSQLITE_ENABLE_MEMSYS5
  -DSQLITE_ENABLE_PERCENTILE -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB
  -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_SELECTTRACE
  -DSQLITE_ENABLE_WHERETRACE -DSQLITE_STRICT_SUBTYPE=1
  -DSQLITE_SERIES_CONSTRAINT_VERIFY=1 -DSQLITE_HAVE_ZLIB=1
)

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cc "${PROD_FLAGS[@]}" -I vendor/tsrc tools/offsets.c -o "$TMP/off_prod" -lm -lz
cc "${TF_FLAGS[@]}"   -I vendor/tsrc tools/offsets.c -o "$TMP/off_tf"   -lm -lz
"$TMP/off_prod" >"$TMP/prod.txt"
"$TMP/off_tf"   >"$TMP/tf.txt"

OUT="$PROJ/src/c_layout.zig"
{
  echo "//! C struct layout ground truth — GENERATED by tools/gen_layout.sh."
  echo "//! Do not edit by hand. Re-run that script after changing tools/offsets.c"
  echo "//! or bumping the vendored SQLite sources."
  echo "//!"
  echo "//! \`pick(name)\` returns the offset/size for the current build config,"
  echo "//! selected by \`@import(\"config\").sqlite_debug\` (true => testfixture)."
  echo ""
  echo "const config = @import(\"config\");"
  echo ""
  echo "/// Production library config (no SQLITE_DEBUG/TEST)."
  echo "const prod = struct {"
  while read -r name val; do echo "    pub const $name: usize = $val;"; done <"$TMP/prod.txt"
  echo "};"
  echo ""
  echo "/// --dev testfixture config (SQLITE_DEBUG + SQLITE_TEST)."
  echo "const tf = struct {"
  while read -r name val; do echo "    pub const $name: usize = $val;"; done <"$TMP/tf.txt"
  echo "};"
  echo ""
  echo "/// The layout namespace matching the current build."
  echo "pub const c = if (config.sqlite_debug) tf else prod;"
} >"$OUT"

echo "wrote $OUT"
echo "--- production vs testfixture diffs ---"
diff <(sort "$TMP/prod.txt") <(sort "$TMP/tf.txt") || true
