//! C struct layout ground truth — GENERATED by tools/gen_layout.sh.
//! Do not edit by hand. Re-run that script after changing tools/offsets.c
//! or bumping the vendored SQLite sources.
//!
//! `pick(name)` returns the offset/size for the current build config,
//! selected by `@import("config").sqlite_debug` (true => testfixture).

const config = @import("config");

/// Production library config (no SQLITE_DEBUG/TEST).
const prod = struct {
    pub const sizeof_Mem: usize = 56;
    pub const sqlite3_value_z: usize = 8;
    pub const sqlite3_value_n: usize = 16;
    pub const sqlite3_value_flags: usize = 20;
    pub const sqlite3_value_enc: usize = 22;
    pub const sqlite3_value_eSubtype: usize = 23;
    pub const sqlite3_value_db: usize = 24;
    pub const sqlite3_value_szMalloc: usize = 32;
    pub const sqlite3_value_uTemp: usize = 36;
    pub const sqlite3_value_zMalloc: usize = 40;
    pub const sqlite3_value_xDel: usize = 48;
    pub const sizeof_sqlite3: usize = 816;
    pub const sqlite3_mallocFailed: usize = 103;
    pub const sqlite3_errCode: usize = 80;
    pub const sizeof_Sqlite3Config: usize = 440;
    pub const Sqlite3Config_iPrngSeed: usize = 432;
    pub const Sqlite3Config_nHeap: usize = 280;
    pub const Sqlite3Config_pHeap: usize = 272;
    pub const Sqlite3Config_mnReq: usize = 284;
    pub const Sqlite3Config_bMemstat: usize = 0;
};

/// --dev testfixture config (SQLITE_DEBUG + SQLITE_TEST).
const tf = struct {
    pub const sizeof_Mem: usize = 72;
    pub const sqlite3_value_z: usize = 8;
    pub const sqlite3_value_n: usize = 16;
    pub const sqlite3_value_flags: usize = 20;
    pub const sqlite3_value_enc: usize = 22;
    pub const sqlite3_value_eSubtype: usize = 23;
    pub const sqlite3_value_db: usize = 24;
    pub const sqlite3_value_szMalloc: usize = 32;
    pub const sqlite3_value_uTemp: usize = 36;
    pub const sqlite3_value_zMalloc: usize = 40;
    pub const sqlite3_value_xDel: usize = 48;
    pub const sizeof_sqlite3: usize = 816;
    pub const sqlite3_mallocFailed: usize = 103;
    pub const sqlite3_errCode: usize = 80;
    pub const sizeof_Sqlite3Config: usize = 488;
    pub const Sqlite3Config_iPrngSeed: usize = 432;
    pub const Sqlite3Config_nHeap: usize = 280;
    pub const Sqlite3Config_pHeap: usize = 272;
    pub const Sqlite3Config_mnReq: usize = 284;
    pub const Sqlite3Config_bMemstat: usize = 0;
};

/// The layout namespace matching the current build.
pub const c = if (config.sqlite_debug) tf else prod;
