//! Zig port of SQLite's compile-time-option reporting (src/ctime.c).
//!
//! Upstream `ctime.c` is GENERATED by `tool/mkctimec.tcl`: it is a big,
//! A-Z-sorted `static const char * const sqlite3azCompileOpt[]` whose entries
//! are each guarded by an `#ifdef`, plus the single non-static function
//! `sqlite3CompileOptions(int*)`. Which strings are emitted depends ENTIRELY on
//! which `SQLITE_*` macros are defined for THIS build, so we do not transcribe
//! the `#ifdef` maze. Instead the exact two string lists below were derived
//! EMPIRICALLY by compiling the real `vendor/tsrc/ctime.c` with this project's
//! flags (see the build-derivation note further down) and dumping the array.
//!
//! Only `sqlite3CompileOptions` lives here. The public APIs
//! `sqlite3_compileoption_get` / `sqlite3_compileoption_used` are part of
//! main.c and are already ported in src/main.zig (they call back into the
//! `sqlite3CompileOptions` exported here).
//!
//! SQLITE_OMIT_COMPILEOPTION_DIAGS is OFF in this build, so the function is
//! present (the `#ifndef` guard around the whole file is satisfied).
//!
//! The strings are stored WITHOUT the "SQLITE_" prefix (the C generator strips
//! it), MUST stay A-Z sorted in C/ASCII (strcmp) order, and MUST match the C
//! output order exactly — `sqlite3_compileoption_used` (in main.zig) scans this
//! array and relies on the entries being the canonical names.
//!
//! Two configs, comptime-selected via `@import("config")`:
//!   * production library   — `sqlite_flags` in build.zig (56 entries)
//!   * testfixture (--dev)  — production + SQLITE_DEBUG + SQLITE_TEST,
//!     which add three entries: DEBUG, NEED_ERR_NAME, TEST (59 entries).
//! `config.sqlite_debug` and `config.sqlite_test` are both set true only for the
//! testfixture build (tools/tcltest.sh), false for the production library, so
//! one object serves both configurations.
//!
//! Build-derivation note (how the lists below were obtained):
//!   A probe that `#include "ctime.c"` and prints every entry of
//!   `sqlite3CompileOptions()` was compiled with `zig cc` and this project's
//!   exact flags. Production:
//!     zig cc -I vendor/tsrc <sqlite_flags> probe.c   -> 56 entries
//!   Testfixture (adds -DSQLITE_DEBUG -DSQLITE_TEST):
//!     zig cc -I vendor/tsrc <sqlite_flags> -DSQLITE_DEBUG -DSQLITE_TEST probe.c
//!                                                    -> 59 entries
//!   Both outputs are A-Z sorted (verified with `LC_ALL=C sort`).
//!
//! COMPILER string: the C generator bakes in the version of the compiler that
//! built the object (`COMPILER=clang-MAJOR.MINOR.PATCH` under clang). The C
//! translation units in this project are built by `zig cc`, whose clang reports
//! `clang-22.1.4` for this toolchain. We bake the same value here so the entry
//! matches the C-built artifact byte-for-byte. No test pins this value (the only
//! upstream references are hardcoded corrupt-DB blobs), so it is purely a
//! build-environment constant exactly like the C `COMPILER=gcc-...` it replaces.

const config = @import("config");

/// `COMPILER=` entry. Mirrors what `zig cc`'s clang emits for this toolchain;
/// see the COMPILER note in the file header.
const compiler_opt: [*:0]const u8 = "COMPILER=clang-22.1.4";

/// Production library option list (mirrors `sqlite_flags` in build.zig).
/// A-Z sorted; entries carry no "SQLITE_" prefix. 56 entries.
const opts_prod = [_][*:0]const u8{
    "ATOMIC_INTRINSICS=1",
    compiler_opt,
    "DEFAULT_AUTOVACUUM",
    "DEFAULT_CACHE_SIZE=-2000",
    "DEFAULT_FILE_FORMAT=4",
    "DEFAULT_JOURNAL_SIZE_LIMIT=-1",
    "DEFAULT_MMAP_SIZE=0",
    "DEFAULT_PAGE_SIZE=4096",
    "DEFAULT_PCACHE_INITSZ=20",
    "DEFAULT_RECURSIVE_TRIGGERS",
    "DEFAULT_SECTOR_SIZE=4096",
    "DEFAULT_SYNCHRONOUS=2",
    "DEFAULT_WAL_AUTOCHECKPOINT=1000",
    "DEFAULT_WAL_SYNCHRONOUS=2",
    "DEFAULT_WORKER_THREADS=0",
    "DIRECT_OVERFLOW_READ",
    "DQS=0",
    "ENABLE_BYTECODE_VTAB",
    "ENABLE_CARRAY",
    "ENABLE_DBPAGE_VTAB",
    "ENABLE_DBSTAT_VTAB",
    "ENABLE_EXPLAIN_COMMENTS",
    "ENABLE_FTS3",
    "ENABLE_FTS4",
    "ENABLE_FTS5",
    "ENABLE_GEOPOLY",
    "ENABLE_MATH_FUNCTIONS",
    "ENABLE_MEMSYS5",
    "ENABLE_OFFSET_SQL_FUNC",
    "ENABLE_PERCENTILE",
    "ENABLE_PREUPDATE_HOOK",
    "ENABLE_RTREE",
    "ENABLE_SESSION",
    "ENABLE_STMTVTAB",
    "ENABLE_UNKNOWN_SQL_FUNCTION",
    "MALLOC_SOFT_LIMIT=1024",
    "MAX_ATTACHED=10",
    "MAX_COLUMN=2000",
    "MAX_COMPOUND_SELECT=500",
    "MAX_DEFAULT_PAGE_SIZE=8192",
    "MAX_EXPR_DEPTH=1000",
    "MAX_FUNCTION_ARG=1000",
    "MAX_LENGTH=1000000000",
    "MAX_LIKE_PATTERN_LENGTH=50000",
    "MAX_MMAP_SIZE=0x7fff0000",
    "MAX_PAGE_COUNT=0xfffffffe",
    "MAX_PAGE_SIZE=65536",
    "MAX_SQL_LENGTH=1000000000",
    "MAX_TRIGGER_DEPTH=1000",
    "MAX_VARIABLE_NUMBER=32766",
    "MAX_VDBE_OP=250000000",
    "MAX_WORKER_THREADS=8",
    "MUTEX_PTHREADS",
    "SYSTEM_MALLOC",
    "TEMP_STORE=1",
    "THREADSAFE=1",
};

/// Testfixture (--dev) option list: production + SQLITE_DEBUG + SQLITE_TEST.
/// The three extra entries (DEBUG, NEED_ERR_NAME, TEST) keep the array A-Z
/// sorted. 59 entries.
const opts_tf = [_][*:0]const u8{
    "ATOMIC_INTRINSICS=1",
    compiler_opt,
    "DEBUG",
    "DEFAULT_AUTOVACUUM",
    "DEFAULT_CACHE_SIZE=-2000",
    "DEFAULT_FILE_FORMAT=4",
    "DEFAULT_JOURNAL_SIZE_LIMIT=-1",
    "DEFAULT_MMAP_SIZE=0",
    "DEFAULT_PAGE_SIZE=4096",
    "DEFAULT_PCACHE_INITSZ=20",
    "DEFAULT_RECURSIVE_TRIGGERS",
    "DEFAULT_SECTOR_SIZE=4096",
    "DEFAULT_SYNCHRONOUS=2",
    "DEFAULT_WAL_AUTOCHECKPOINT=1000",
    "DEFAULT_WAL_SYNCHRONOUS=2",
    "DEFAULT_WORKER_THREADS=0",
    "DIRECT_OVERFLOW_READ",
    "DQS=0",
    "ENABLE_BYTECODE_VTAB",
    "ENABLE_CARRAY",
    "ENABLE_DBPAGE_VTAB",
    "ENABLE_DBSTAT_VTAB",
    "ENABLE_EXPLAIN_COMMENTS",
    "ENABLE_FTS3",
    "ENABLE_FTS4",
    "ENABLE_FTS5",
    "ENABLE_GEOPOLY",
    "ENABLE_MATH_FUNCTIONS",
    "ENABLE_MEMSYS5",
    "ENABLE_OFFSET_SQL_FUNC",
    "ENABLE_PERCENTILE",
    "ENABLE_PREUPDATE_HOOK",
    "ENABLE_RTREE",
    "ENABLE_SESSION",
    "ENABLE_STMTVTAB",
    "ENABLE_UNKNOWN_SQL_FUNCTION",
    "MALLOC_SOFT_LIMIT=1024",
    "MAX_ATTACHED=10",
    "MAX_COLUMN=2000",
    "MAX_COMPOUND_SELECT=500",
    "MAX_DEFAULT_PAGE_SIZE=8192",
    "MAX_EXPR_DEPTH=1000",
    "MAX_FUNCTION_ARG=1000",
    "MAX_LENGTH=1000000000",
    "MAX_LIKE_PATTERN_LENGTH=50000",
    "MAX_MMAP_SIZE=0x7fff0000",
    "MAX_PAGE_COUNT=0xfffffffe",
    "MAX_PAGE_SIZE=65536",
    "MAX_SQL_LENGTH=1000000000",
    "MAX_TRIGGER_DEPTH=1000",
    "MAX_VARIABLE_NUMBER=32766",
    "MAX_VDBE_OP=250000000",
    "MAX_WORKER_THREADS=8",
    "MUTEX_PTHREADS",
    "NEED_ERR_NAME",
    "SYSTEM_MALLOC",
    "TEMP_STORE=1",
    "TEST",
    "THREADSAFE=1",
};

/// Comptime-selected table. Testfixture (--dev) iff both DEBUG and TEST are set
/// (build.zig sets `sqlite_debug` and `sqlite_test` together via -Dtestfixture);
/// otherwise the production list.
const azCompileOpt = if (config.sqlite_debug and config.sqlite_test) &opts_tf else &opts_prod;

/// C ABI: `const char **sqlite3CompileOptions(int *pnOpt)`.
/// Writes the option count to `pnOpt` and returns the (A-Z sorted) array of
/// option-name strings. The returned pointer is to static storage.
export fn sqlite3CompileOptions(pnOpt: *c_int) callconv(.c) ?[*]const ?[*:0]const u8 {
    pnOpt.* = @intCast(azCompileOpt.len);
    // [N][*:0]const u8 -> [*]const ?[*:0]const u8 : same representation
    // (array of non-null string pointers, viewed as nullable string pointers).
    return @ptrCast(azCompileOpt);
}
